[package]
name = "satisfactory-extractor"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true }
regex = {workspace = true, features = []}